name: Update Schedule

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # This is important!
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Add this line

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 PyGithub

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update schedule" || exit 0
        git push
